name: Check Grammarly Jobs

on:
  schedule:
    - cron: "0 10 * * *"  # Запуск щодня о 12:00 за Києвом (10:00 UTC)
  workflow_dispatch:  # Можна запустити вручну

jobs:
  check-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v3

      - name: Встановлення Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Встановлення залежностей
        run: pip install -r requirements.txt

      - name: Запуск скрипта
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
